INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('panic disorder', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('vocal cord polyp', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('turner syndrome', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('injury to internal organ', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('cryptorchidism', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('poisoning due to ethylene glycol', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('atrophic vaginitis', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('fracture of the hand', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('cellulitis or abscess of mouth', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('eye alignment disorder', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('headache after lumbar puncture', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pyloric stenosis', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('salivary gland disorder', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('osteochondrosis', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('injury to the knee', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('metabolic disorder', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('vaginitis', 4);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('sick sinus syndrome', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('tinnitus of unknown cause', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('glaucoma', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('eating disorder', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('transient ischemic attack', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pyelonephritis', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('rotator cuff injury', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('chronic pain disorder', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('problem during pregnancy', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('liver cancer', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('atelectasis', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('injury to the hand', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('choledocholithiasis', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('injury to the hip', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('cirrhosis', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('thoracic aortic aneurysm', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('subdural hemorrhage', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('diabetic retinopathy', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('fibromyalgia', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('ischemia of the bowel', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('fetal alcohol syndrome', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('peritonitis', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('injury to the abdomen', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('acute pancreatitis', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('thrombophlebitis', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('asthma', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('foreign body in the vagina', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('restless leg syndrome', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('emphysema', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('cysticercosis', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('induced abortion', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('teething syndrome', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('infectious gastroenteritis', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('acute sinusitis', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('substance-related mental disorder', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('postpartum depression', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('coronary atherosclerosis', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('spondylitis', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pituitary adenoma', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('uterine fibroids', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('idiopathic nonmenstrual bleeding', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('chalazion', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('ovarian torsion', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('retinopathy due to high blood pressure', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('vaginal yeast infection', 4);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('mastoiditis', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('lung contusion', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hypertrophic obstructive cardiomyopathy (hocm)', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('ingrown toe nail', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pulmonary eosinophilia', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('corneal disorder', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('foreign body in the gastrointestinal tract', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('endophthalmitis', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('intestinal malabsorption', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('viral warts', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hyperhidrosis', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('stroke', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pilonidal cyst', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('crushing injury', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('normal pressure hydrocephalus', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('alopecia', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hashimoto thyroiditis', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('flat feet', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('nonalcoholic liver disease (nash)', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hemarthrosis', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pelvic organ prolapse', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('fracture of the arm', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('coagulation (bleeding) disorder', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('intracranial hemorrhage', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hyperkalemia', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('cornea infection', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('abscess of the lung', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('dengue fever', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('chronic sinusitis', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('cholesteatoma', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('volvulus', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('injury to the finger', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('poisoning due to analgesics', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('atrial fibrillation', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pinworm infection', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('urethral valves', 4);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('open wound of the neck', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('achalasia', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('conductive hearing loss', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('abdominal hernia', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('cerebral palsy', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('marijuana abuse', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('cryptococcosis', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('obesity', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('indigestion', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('bursitis', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('esophageal cancer', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pulmonary congestion', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('juvenile rheumatoid arthritis', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('actinic keratosis', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('acute otitis media', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('astigmatism', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('tuberous sclerosis', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('empyema', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('presbyacusis', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('neonatal jaundice', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('chronic obstructive pulmonary disease (copd)', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('dislocation of the elbow', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('spondylosis', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('herpangina', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('injury to the shoulder', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('poisoning due to antidepressants', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('infection of open wound', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('deep vein thrombosis (dvt)', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('protein deficiency', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('myoclonus', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('bone spur of the calcaneous', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('von willebrand disease', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('open wound of the back', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('heart block', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('colonic polyp', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('magnesium deficiency', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('female infertility of unknown cause', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pericarditis', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('attention deficit hyperactivity disorder (adhd)', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pulmonic valve disease', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('tietze syndrome', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('cranial nerve palsy', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('injury to the arm', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('conversion disorder', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('complex regional pain syndrome', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('otosclerosis', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('injury to the trunk', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hypothyroidism', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('primary insomnia', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('lice', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('vitamin b12 deficiency', 12);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('diabetes', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('vulvodynia', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('endometriosis', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('vasculitis', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('concussion', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('oral leukoplakia', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('chronic kidney disease', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('bladder disorder', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('chorioretinitis', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('priapism', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('myositis', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('mononucleosis', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('neuralgia', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('polycystic kidney disease', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('bipolar disorder', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('amyloidosis', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('chronic inflammatory demyelinating polyneuropathy (cidp)', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('gastroesophageal reflux disease (gerd)', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('vitreous hemorrhage', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('poisoning due to antimicrobial drugs', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('open wound of the mouth', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('scleroderma', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('myasthenia gravis', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hypoglycemia', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('idiopathic absence of menstruation', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('dislocation of the ankle', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('carbon monoxide poisoning', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('panic attack', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('plantar fasciitis', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hyperopia', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('poisoning due to sedatives', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pemphigus', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('peyronie disease', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hiatal hernia', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('extrapyramidal effect of drugs', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('meniere disease', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('anal fissure', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('allergy', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('chronic otitis media', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('fracture of the finger', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hirschsprung disease', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('polymyalgia rheumatica', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('lymphedema', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('bladder cancer', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('acute bronchospasm', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('acute glaucoma', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('open wound of the chest', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('dislocation of the patella', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('sciatica', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hypercalcemia', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('stress incontinence', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('varicose veins', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('benign kidney cyst', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hydrocele of the testicle', 4);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('degenerative disc disease', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hirsutism', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('dislocation of the foot', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hydronephrosis', 4);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('diverticulosis', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pain after an operation', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('huntington disease', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('lymphoma', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('dermatitis due to sun exposure', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('anemia due to chronic kidney disease', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('scleritis', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pterygium', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('fungal infection of the skin', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('insulin overdose', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('syndrome of inappropriate secretion of adh (siadh)', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('foreign body in the ear', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('premenstrual tension syndrome', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('orbital cellulitis', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('injury to the leg', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hepatic encephalopathy', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('bone cancer', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('syringomyelia', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pulmonary fibrosis', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('mitral valve disease', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('parkinson disease', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('gout', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('otitis media', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('drug abuse (opioids)', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('myelodysplastic syndrome', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('fracture of the shoulder', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('acute kidney injury', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('threatened pregnancy', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('intracranial abscess', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('gum disease', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('open wound from surgical incision', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('gastrointestinal hemorrhage', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('seborrheic dermatitis', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('drug abuse (methamphetamine)', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('torticollis', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('poisoning due to antihypertensives', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('tension headache', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('alcohol intoxication', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('scurvy', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('narcolepsy', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('food allergy', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('labyrinthitis', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('anxiety', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('impulse control disorder', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('stenosis of the tear duct', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('abscess of nose', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('omphalitis', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('leukemia', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('bell palsy', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('conjunctivitis due to allergy', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('drug reaction', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('adrenal cancer', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('myopia', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('osteoarthritis', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('thyroid disease', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pharyngitis', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('chronic rheumatic fever', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hypocalcemia', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('macular degeneration', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pneumonia', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('optic neuritis', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('cold sore', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('premature ventricular contractions (pvcs)', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('testicular cancer', 4);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hydrocephalus', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('breast cancer', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('anemia due to malignancy', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('esophageal varices', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('endometrial cancer', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('cystic fibrosis', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('intertrigo (skin condition)', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('parathyroid adenoma', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('glucocorticoid deficiency', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('temporomandibular joint disorder', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('wilson disease', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('vesicoureteral reflux', 4);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('vitamin a deficiency', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('gonorrhea', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('fracture of the rib', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('ependymoma', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hepatitis due to a toxin', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('vaginal cyst', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('open wound of the shoulder', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('ectopic pregnancy', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('chronic knee pain', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pinguecula', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hypergammaglobulinemia', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('alcohol abuse', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('carpal tunnel syndrome', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pituitary disorder', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('kidney stone', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('autism', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('cat scratch disease', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('chronic glaucoma', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('retinal detachment', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('aplastic anemia', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('overflow incontinence', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hemolytic anemia', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('lateral epicondylitis (tennis elbow)', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('open wound of the eye', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('syphilis', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('diabetic kidney disease', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('nose disorder', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('drug withdrawal', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('dental caries', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hypercholesterolemia', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('fracture of the patella', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('kidney failure', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('fracture of the neck', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('muscle spasm', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hemophilia', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hyperosmotic hyperketotic state', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('peritonsillar abscess', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('gastroparesis', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('itching of unknown cause', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('polycythemia vera', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('thrombocytopenia', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('head and neck cancer', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pseudohypoparathyroidism', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('goiter', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('urge incontinence', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('edward syndrome', 18);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('open wound of the arm', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('muscular dystrophy', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('mittelschmerz', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('corneal abrasion', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('anemia of chronic disease', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('dysthymic disorder', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('scarlet fever', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hypertensive heart disease', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('drug abuse (barbiturates)', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('polycystic ovarian syndrome (pcos)', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('encephalitis', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('cyst of the eyelid', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('balanitis', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('foreign body in the throat', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('drug abuse (cocaine)', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('alcohol withdrawal', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('premature atrial contractions (pacs)', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hemiplegia', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hammer toe', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('open wound of the cheek', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('joint effusion', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('open wound of the knee', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('meningioma', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('brain cancer', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('placental abruption', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('seasonal allergies (hay fever)', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('lung cancer', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('primary kidney disease', 4);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('uterine cancer', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('dry eye of unknown cause', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('fibrocystic breast disease', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('fungal infection of the hair', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('tooth abscess', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('envenomation from spider or animal bite', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('vacterl syndrome', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('vertebrobasilar insufficiency', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('rectal disorder', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('atonic bladder', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('benign paroxysmal positional vertical (bppv)', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('blepharospasm', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('sarcoidosis', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('metastatic cancer', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('trigger finger (finger disorder)', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('stye', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hemochromatosis', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('osteochondroma', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('cushing syndrome', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('typhoid fever', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('vitreous degeneration', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('atrophic skin condition', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('aspergillosis', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('uterine atony', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('trichinosis', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('whooping cough', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('open wound of the lip', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('subacute thyroiditis', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('oral mucosal lesion', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('open wound due to trauma', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('intracerebral hemorrhage', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('alzheimer disease', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('vaginismus', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('systemic lupus erythematosis (sle)', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('premature ovarian failure', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('thoracic outlet syndrome', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('ganglion cyst', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('dislocation of the knee', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('crohn disease', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('postoperative infection', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('folate deficiency', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('fluid overload', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('atrial flutter', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('skin disorder', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('floaters', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('tooth disorder', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('heart attack', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('open wound of the abdomen', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('fracture of the leg', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('oral thrush (yeast infection)', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pityriasis rosea', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('allergy to animals', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('orthostatic hypotension', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('obstructive sleep apnea (osa)', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hypokalemia', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('psoriasis', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('dislocation of the shoulder', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('intussusception', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('cervicitis', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('abscess of the pharynx', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('primary thrombocythemia', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('arthritis of the hip', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('decubitus ulcer', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hypernatremia', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('sensorineural hearing loss', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('chronic ulcer', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('osteoporosis', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('ileus', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('sickle cell crisis', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('urethritis', 4);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('prostatitis', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('otitis externa (swimmer''s ear)', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('poisoning due to anticonvulsants', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('testicular torsion', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('tricuspid valve disease', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('urethral stricture', 4);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('vitamin d deficiency', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hydatidiform mole', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pain disorder affecting the neck', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('tuberculosis', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pelvic fistula', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('acute bronchiolitis', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('presbyopia', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('dementia', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('insect bite', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('paroxysmal ventricular tachycardia', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('congenital heart defect', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('connective tissue disorder', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('foreign body in the eye', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('poisoning due to gas', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pyogenic skin infection', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('endometrial hyperplasia', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('acanthosis nigricans', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('central atherosclerosis', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('viral exanthem', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('noninfectious gastroenteritis', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('benign prostatic hyperplasia (bph)', 4);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('menopause', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('primary immunodeficiency', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('ovarian cancer', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('cataract', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('dislocation of the hip', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('spinal stenosis', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('intestinal obstruction', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('heart contusion', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('congenital malformation syndrome', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('sporotrichosis', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('lymphangitis', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('wernicke korsakoff syndrome', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('intestinal disease', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('acute bronchitis', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('persistent vomiting of unknown cause', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('open wound of the foot', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('myocarditis', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('preeclampsia', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('ischemic heart disease', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('neurofibromatosis', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('chickenpox', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pancreatic cancer', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('neuropathy due to drugs', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('croup', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('idiopathic excessive menstruation', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('amblyopia', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('meckel diverticulum', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('dislocation of the wrist', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('ear drum damage', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('erectile dysfunction', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('temporary or benign blood in urine', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('kidney disease due to longstanding hypertension', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('chondromalacia of the patella', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('onychomycosis', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('urethral disorder', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('lyme disease', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('iron deficiency anemia', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('acute respiratory distress syndrome (ards)', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('toxic multinodular goiter', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('open wound of the finger', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('autonomic nervous system disorder', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('psychosexual disorder', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('anemia', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('tendinitis', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('common cold', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('amyotrophic lateral sclerosis (als)', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('central retinal artery or vein occlusion', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('paroxysmal supraventricular tachycardia', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('venous insufficiency', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('trichomonas infection', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('acne', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('depression', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('drug abuse', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('urinary tract obstruction', 4);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('diabetes insipidus', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('iridocyclitis', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('varicocele of the testicles', 4);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('irritable bowel syndrome', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('fracture of the foot', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('ovarian cyst', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('chlamydia', 4);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('parasitic disease', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('fracture of the jaw', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('lipoma', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('female genitalia infection', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pulmonary hypertension', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('thyroid nodule', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('broken tooth', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('dumping syndrome', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('lymphadenitis', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('injury to the face', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('aortic valve disease', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('rheumatoid arthritis', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('spermatocele', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('impetigo', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('anal fistula', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hypothermia', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('oppositional disorder', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('migraine', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('diabetic peripheral neuropathy', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('testicular disorder', 4);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('gestational diabetes', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hidradenitis suppurativa', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('valley fever', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('conjunctivitis due to bacteria', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('lewy body dementia', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('multiple myeloma', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('head injury', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('ascending cholangitis', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('idiopathic irregular menstrual cycle', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('interstitial lung disease', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('mononeuritis', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('malaria', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('somatization disorder', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hypovolemia', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('schizophrenia', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('knee ligament or meniscus tear', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('endocarditis', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('sepsis', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('heat stroke', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('cholecystitis', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('cardiac arrest', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('cardiomyopathy', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('social phobia', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('meningitis', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('spherocytosis', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hormone disorder', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('raynaud disease', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('reactive arthritis', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('scabies', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('ear wax impaction', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hypertension of pregnancy', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('peripheral arterial embolism', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('rosacea', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('fracture of the skull', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('uveitis', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('fracture of the facial bones', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('tracheitis', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('jaw disorder', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('perirectal infection', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('breast cyst', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('post-traumatic stress disorder (ptsd)', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('kidney cancer', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('vulvar cancer', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('blepharitis', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('celiac disease', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('cystitis', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('sickle cell anemia', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('subconjunctival hemorrhage', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hemorrhoids', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('contact dermatitis', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('sinus bradycardia', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('high blood pressure', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pelvic inflammatory disease', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('liver disease', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('chronic constipation', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('thyroid cancer', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('flu', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('friedrich ataxia', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('tic (movement) disorder', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('skin polyp', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('brachial neuritis', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('cervical cancer', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('adrenal adenoma', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('esophagitis', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('gas gangrene', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('yeast infection', 4);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('spina bifida', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('drug poisoning due to medication', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('alcoholic liver disease', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('malignant hypertension', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('diverticulitis', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('moyamoya disease', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('heat exhaustion', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('psychotic disorder', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('frostbite', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('atrophy of the corpus cavernosum', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('smoking or tobacco addiction', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('sprain or strain', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('essential tremor', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('open wound of the ear', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('foreign body in the nose', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('idiopathic painful menstruation', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('down syndrome', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('idiopathic infrequent menstruation', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pneumothorax', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('de quervain disease', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('fracture of the vertebra', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('human immunodeficiency virus infection (hiv)', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('mumps', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('subarachnoid hemorrhage', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('acute fatty liver of pregnancy (aflp)', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('ectropion', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('scar', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('lactose intolerance', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('eustachian tube dysfunction (ear disorder)', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('appendicitis', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('graves disease', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('dissociative disorder', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('open wound of the face', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('dislocation of the vertebra', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('phimosis', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hyperemesis gravidarum', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pregnancy', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('thalassemia', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('placenta previa', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('epidural hemorrhage', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('septic arthritis', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('athlete''s foot', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pleural effusion', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('aphakia', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('vulvar disorder', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('sialoadenitis', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('gynecomastia', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('urinary tract infection', 4);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('histoplasmosis', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('erythema multiforme', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('scoliosis', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('bunion', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('arrhythmia', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('trigeminal neuralgia', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('ankylosing spondylitis', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('peripheral nerve disorder', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('sebaceous cyst', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('poisoning due to antipsychotics', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('neurosis', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('prostate cancer', 4);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('cerebral edema', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('dislocation of the finger', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('birth trauma', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('chronic pancreatitis', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hematoma', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('carcinoid syndrome', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('open wound of the head', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('seborrheic keratosis', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('burn', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('spontaneous abortion', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('genital herpes', 4);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('adjustment reaction', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('gallstone', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('multiple sclerosis', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('zenker diverticulum', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('fracture of the pelvis', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pneumoconiosis', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hyperlipidemia', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('ulcerative colitis', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('male genitalia infection', 4);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hpv', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('angina', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('injury to the spinal cord', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('nasal polyp', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('lichen simplex', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('trichiasis', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('acariasis', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('colorectal cancer', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('skin pigmentation disorder', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('factitious disorder', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('lymphogranuloma venereum', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('galactorrhea of unknown cause', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('g6pd enzyme deficiency', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('nerve impingement near the shoulder', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('toxoplasmosis', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('fibroadenoma', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('open wound of the hand', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('missed abortion', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('diabetic ketoacidosis', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('granuloma inguinale', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('obsessive compulsive disorder (ocd)', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('injury of the ankle', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hyponatremia', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('stricture of the esophagus', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('fracture of the ankle', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('soft tissue sarcoma', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('bone disorder', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('epilepsy', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('personality disorder', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('shingles (herpes zoster)', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('tourette syndrome', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('avascular necrosis', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('strep throat', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('spinocerebellar ataxia', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('osteomyelitis', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('sjogren syndrome', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('adhesive capsulitis of the shoulder', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('viral hepatitis', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('tonsillar hypertrophy', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('gastritis', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('skin cancer', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('rheumatic fever', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('aphthous ulcer', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('tonsillitis', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('intestinal cancer', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('rocky mountain spotted fever', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('stomach cancer', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('developmental disability', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('acute stress reaction', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('delirium', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('callus', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('guillain barre syndrome', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('lumbago', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('deviated nasal septum', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('hemangioma', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('peripheral arterial disease', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('chronic back pain', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('heart failure', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('conjunctivitis', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('herniated disk', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('rhabdomyolysis', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('breast infection (mastitis)', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('abdominal aortic aneurysm', 8);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pulmonary embolism', 2);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('conduct disorder', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('mastectomy', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('epididymitis', 4);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('premature rupture of amniotic membrane', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('molluscum contagiosum', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('necrotizing fasciitis', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('benign vaginal discharge (leukorrhea)', 4);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('bladder obstruction', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('melanoma', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('cervical disorder', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('laryngitis', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('dyshidrosis', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('poisoning due to opioids', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('diaper rash', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('lichen planus', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('gastroduodenal ulcer', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('inguinal hernia', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('eczema', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('asperger syndrome', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('mucositis', 3);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('paronychia', 6);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('open wound of the jaw', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('white blood cell disease', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('kaposi sarcoma', 9);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('spondylolisthesis', 5);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('pseudotumor cerebri', 1);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('conjunctivitis due to virus', 7);
INSERT INTO classification_symptoms (name, classification_symptom_group_id) VALUES ('open wound of the nose', 7);